_meta:
  type: "config"
  config_version: 2

config:
  dynamic:
    authc:
      openid_auth_domain:
        http_enabled: true
        transport_enabled: true
        order: 0
        http_authenticator:
          type: openid
          challenge: false
          config:
            subject_key: preferred_username
            roles_key: roles
            openid_connect_url: "https://cmp-keycloak-iam.apps.pvc-os-caas01-rs.polostrategiconazionale.it/auth"
        authentication_backend:
          type: noop
